### ISSUE TITLE
用CIFS保存聊天记录时，无法登录

### ISSUE THREAD

**Issue by UnspokenSpell** [RICwang/docker-wechat#17]
![2024-12-13_15-27-34](https://github.com/user-attachments/assets/913967c4-2e51-4954-9c49-fda39ae9d69f)
如果使用CIFS，那么会在登录时卡在"正在进入"。即使等待8H以上也依旧。

我的Docker Compose
```yaml
name: wechat
services:
  wechat:
    image: ricwang/docker-wechat:latest
    container_name: wechat
    volumes:
      - /app/WeChat/.xwechat:/root/.xwechat # 程序配置
      - Chat_History:/root/xwechat_files # 聊天记录
      - File_Interaction:/root/downloads # 文件交互
      - /dev/snd:/dev/snd
    ports:
      - 5800:5800
      - 5900:5900
    environment:
      - LANG=zh_CN.UTF-8
      - USER_ID=0
      - GROUP_ID=0
      - WEB_AUDIO=1
      - TZ=Asia/Shanghai  
    privileged: true

volumes:
  Chat_History:
      driver_opts:
        type: "cifs"
        o: "addr=192.168.5.21,username=admin,password=admin,dir_mode=0755,file_mode=0755,vers=3.0"
        device: "//192.168.5.21/pool_1/Service/App_Data/WeChat/xwechat_files"
  File_Interaction:
      driver_opts:
        type: "cifs"
        o: "addr=192.168.5.21,username=admin,password=admin,dir_mode=0755,file_mode=0777,vers=3.0"
        device: "//192.168.5.25/pool_1/Temporary"
```
