### ISSUE TITLE
新的方案，可以解决中文输入法和呼叫崩溃问题，集成火狐浏览器

### ISSUE THREAD

**Issue by randydl** [RICwang/docker-wechat#23]
Dockerfile
```
FROM linuxserver/firefox:latest

RUN apt-get update && \
    apt-get install -y wget libatomic1 libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-render-util0 libxcb-keysyms1 desktop-file-utils fonts-noto-cjk-extra

RUN wget https://dldir1v6.qq.com/weixin/Universal/Linux/WeChatLinux_x86_64.deb -O /wechat.deb && \
    apt-get install -y /wechat.deb

ADD menu.xml /defaults/menu.xml
RUN fc-cache -fv
```

menu.xml
```
<?xml version="1.0" encoding="utf-8"?>
<openbox_menu xmlns="http://openbox.org/3.4/menu">
<menu id="root-menu" label="MENU">
<item label="xterm" icon="/usr/share/pixmaps/xterm-color_48x48.xpm"><action name="Execute"><command>/usr/bin/xterm</command></action></item>
<item label="wechat" icon="/usr/share/icons/hicolor/48x48/apps/wechat.png"><action name="Execute"><command>/usr/bin/wechat</command></action></item>
<item label="firefox" icon="/usr/share/icons/hicolor/48x48/apps/firefox.png"><action name="Execute"><command>/usr/bin/firefox</command></action></item>
</menu>
</openbox_menu>
```

**Comment by itning** [comment]
@randydl 能打个镜像么

**Comment by randydl** [comment]
```bash
docker pull deepcv/wechat:latest
```

```yaml
services:
  wechat:
    image: deepcv/wechat:latest
    container_name: wechat
    environment:
      - PUID=1000
      - PGID=1000
      - INTERVAL=5
      - TITLE=WeChat
      - TZ=Asia/Shanghai
      - LC_ALL=zh_CN.UTF-8
    ports:
      - 13000:3000
    volumes:
      - /volume2/docker/wechat:/config
    network_mode: bridge
    restart: always
```
